.PHONY: clean All

All:
	@echo "----------Building project:[ PrimitiveDataRypes - Debug ]----------"
	@cd "PrimitiveDataRypes" && "$(MAKE)" -f  "PrimitiveDataRypes.mk"
clean:
	@echo "----------Cleaning project:[ PrimitiveDataRypes - Debug ]----------"
	@cd "PrimitiveDataRypes" && "$(MAKE)" -f  "PrimitiveDataRypes.mk" clean
