.PHONY: clean All

All:
	@echo "----------Building project:[ ArrayElements - Debug ]----------"
	@cd "ArrayElements" && "$(MAKE)" -f  "ArrayElements.mk"
clean:
	@echo "----------Cleaning project:[ ArrayElements - Debug ]----------"
	@cd "ArrayElements" && "$(MAKE)" -f  "ArrayElements.mk" clean
