.PHONY: clean All

All:
	@echo "----------Building project:[ InputsandOutputs - Debug ]----------"
	@cd "InputsandOutputs" && "$(MAKE)" -f  "InputsandOutputs.mk"
clean:
	@echo "----------Cleaning project:[ InputsandOutputs - Debug ]----------"
	@cd "InputsandOutputs" && "$(MAKE)" -f  "InputsandOutputs.mk" clean
