.PHONY: clean All

All:
	@echo "----------Building project:[ Section5 - Debug ]----------"
	@cd "Section5" && "$(MAKE)" -f  "Section5.mk"
clean:
	@echo "----------Cleaning project:[ Section5 - Debug ]----------"
	@cd "Section5" && "$(MAKE)" -f  "Section5.mk" clean
